language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      dist: trusty
    - os: osx
      rust: nightly

cache:
    cargo: true

addons:
  apt:
    packages:
      - libgtk-3-dev

before_install:
    - sh ci/before_install.sh

script:
    - rustc --version
    - cargo build
