language: rust

matrix:
  include:
    - os: linux
      rust: stable
      dist: bionic
    - os: osx
      rust: stable

addons:
  apt:
    packages:
      - libgtk-3-dev

cache:
  cargo: true

before_install:
  - . ci/before_install.sh

script:
  - rustc --version
  - cargo build
