language: rust

env:
  - GTK=3.18

matrix:
  include:
    - os: linux
      rust: nightly
      dist: trusty
    - os: osx
      rust: nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

cache:
  cargo: false

before_install:
  - . ci/before_install.sh

script:
  - rustc --version
  - cargo build
